// <auto-generated />
namespace MyABP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Abp_MoveTo_Mysql : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Abp_MoveTo_Mysql));
        
        string IMigrationMetadata.Id
        {
            get { return "201804021052081_Abp_MoveTo_Mysql"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
